insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-7-12',trim(' 中国好声音盲选第一期《也许明天》'),trim(' 中国好声音盲选第一期《也许明天》'));
insert into bellawiki_file (`url`,`name`) values (trim('http://tv.sohu.com/20130712/n381487508.shtml'),trim('《中国好声音第二季片花》 第一期 姚贝娜《也许明天》 '));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-7-19',trim(' 酷我真声音'),trim(' 酷我真声音'));
insert into bellawiki_file (`url`,`name`) values (trim('http://tv.sohu.com/20130719/n382128142.shtml'),trim('《中国好声音第二季之酷我真声音》20130719 第二期 姚贝娜澄清刘欢徒弟传闻 回忆化疗经历 '));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-8-16',trim(' 中国好声音导师考核第六期'),trim(' 中国好声音导师考核第六期 姚贝娜VS林育群《自己》'));
insert into bellawiki_file (`url`,`name`) values (trim('http://tv.sohu.com/20130816/n384373399.shtml'),trim('《中国好声音第二季片花》第六期 姚贝娜VS林育群《自己》 '));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-8-17',trim(' 好声音百场演出宁波站'),trim(' 好声音百场演出宁波站'));
insert into bellawiki_file (`url`,`name`) values (trim('http://v.youku.com/v_show/id_XNjAzNDIyNjA4.html'),trim('姚贝娜宁波演出live 《红颜劫》《我要的很简单》《也许明天》'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-8-25',trim(' 浙江台庆'),trim(' 浙江台庆 姚贝娜VS金池《也许明天》'));
insert into bellawiki_file (`url`,`name`) values (trim('http://tv.sohu.com/20130824/n384983333.shtml'),trim('《中国蓝5动梦想片花》金池VS姚贝娜《也许明天》 '));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-9-13',trim(' 中国好声音终极考核36进16'),trim(' 中国好声音终极考核36进16 《也许在》'));
insert into bellawiki_file (`url`,`name`) values (trim('http://tv.sohu.com/20130913/n386561641.shtml'),trim('《中国好声音第二季片花》第十期 朱克VS倪鹏VS姚贝娜    '));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-9-19',trim(' 中秋特辑'),trim('  中秋特辑 姚贝娜《也许明天》'));
insert into bellawiki_file (`url`,`name`) values (trim('http://tv.sohu.com/20130919/n386893294.shtml'),trim('《中国好声音第二季演唱会片花》中秋特辑 姚贝娜《也许明天》 '));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-9-20',trim(' 中国好声音那英组四进一'),trim(' 中国好声音那英组四进一《妥协之歌》'));
insert into bellawiki_file (`url`,`name`) values (trim('http://tv.sohu.com/20130920/n386914896.shtml'),trim('《中国好声音第二季片花》第十一期 那英组冠军之战：开场秀《妥协之歌》 '));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into bellawiki_file (`url`,`name`) values (trim('http://tv.sohu.com/20130920/n386915052.shtml'),trim('《中国好声音第二季片花》第十一期 那英组冠军之战：姚贝娜《把握》 '));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into bellawiki_file (`url`,`name`) values (trim('http://tv.sohu.com/20130920/n386915463.shtml'),trim('《中国好声音第二季片花》第十一期 那英组冠军之战：姚贝娜《Dear friend》 '));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into bellawiki_file (`url`,`name`) values (trim('http://tv.sohu.com/20130920/n386915833.shtml'),trim('《中国好声音第二季片花》第十一期 那英组冠军之战：姚贝娜《All by Myself》 '));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-9-23',trim('新疆库尔勒汇嘉时代广场招商峰会'),trim(' 新疆库尔勒汇嘉时代广场招商峰会，视频待补充     '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-9-26',trim('北京大学肿瘤医院慰问乳腺癌患者'),trim(' 北京大学肿瘤医院慰问乳腺癌患者，获颁“北京大学肿瘤医院健康公益大使” 姚贝娜生日医院探望癌症患者+传递正能量+'));
insert into bellawiki_file (`url`,`name`) values (trim('http://tv.sohu.com/20130927/n387333612.shtml'),trim('《中国好声音第二季独家猛料》姚贝娜生日医院探望癌症患者 传递正能量  '));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-9-26',trim('2013粉红丝带乳腺癌防治运动粉红庆典'),trim(' 2013粉红丝带乳腺癌防治运动粉红庆典 成为2013年度粉红丝带明星代言人 姚贝娜性感着装亮相 满意“好声音”赛后收益'));
insert into bellawiki_file (`url`,`name`) values (trim('http://tv.sohu.com/20130927/n387339351.shtml'),trim('《中国好声音第二季视频报道》姚贝娜性感着装亮相 满意“好声音”赛后收益 '));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-10-7',trim('中国好声音巅峰之夜'),trim(' 中国好声音巅峰之夜《龙的传人》'));
insert into bellawiki_file (`url`,`name`) values (trim('http://tv.sohu.com/20131007/n387678391.shtml'),trim('《中国好声音第二季片花》第十五期 年度盛典：十六强开场秀《龙的传人》 '));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-10-8',trim('英雄谱第七期'),trim(' 英雄谱第七期 姚贝娜澄清“甩手”传闻 闺蜜爆料情史'));
insert into bellawiki_file (`url`,`name`) values (trim('http://tv.sohu.com/20131008/n387698333.shtml'),trim('《英雄谱》20131008 第七期 姚贝娜澄清“甩手”传闻 闺蜜爆料情史 '));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-10-8',trim(' 录制歌曲 《我爱我家》姐妹篇《我们一家人》'),trim(' 录制歌曲 《我爱我家》姐妹篇《我们一家人》 英达称全家是姚贝娜歌迷'));
insert into bellawiki_file (`url`,`name`) values (trim('http://www.letv.com/ptv/vplay/2137106.html'),trim('英达称全家是姚贝娜歌迷 曝毛阿敏素颜难辨认'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-10-9',trim(' 青岛辽宁舰慰问演出'),trim(' 青岛辽宁舰慰问演出，待补充 '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-10-11',trim(' 全新单曲《心火》首播'),trim(' 全新单曲《心火》首播'));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-10-12',trim('北京朝北大悦城2013Music Radio 爱.回家爱心助学行动'),trim(' 北京朝北大悦城2013Music Radio 爱.回家爱心助学行动 姚贝娜北京朝北大悦城公益活动完整现场版'));
insert into bellawiki_file (`url`,`name`) values (trim('http://v.youku.com/v_show/id_XNjIwNzQ4OTg4.html'),trim('20131012姚贝娜北京朝北大悦城公益活动完整现场版'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-8-31',trim(' 上海电信见面会'),trim(' 上海电信见面会《也许明天》'));
insert into bellawiki_file (`url`,`name`) values (trim('http://www.tudou.com/programs/view/coNuCUBj0ag/'),trim('姚贝娜上海电信见面会  也许明天'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-9-11',trim(' 姚贝娜首秀演技 《仙变》微电影声动发布'),trim(' 姚贝娜首秀演技 《仙变》微电影声动发布'));
insert into bellawiki_file (`url`,`name`) values (trim('http://tv.sohu.com/20130911/n386393106.shtml'),trim('姚贝娜首秀演技 《仙变》微电影声动发布 '));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-10-13',trim(' 好声音百城百场演唱会西安站'),trim(' 好声音百城百场演唱会西安站（108分钟开始）'));
insert into bellawiki_file (`url`,`name`) values (trim('http://tv.sohu.com/20131024/n388844990.shtml'),trim('西安站全程 朱克送歌迷礼物 姚贝娜献唱甄嬛传'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-10-13',trim(' 北京电视台文艺频道每日文娱播报'),trim(' 北京电视台文艺频道每日文娱播报 上 姚贝娜为何爆冷出局'));
insert into bellawiki_file (`url`,`name`) values (trim('http://my.tv.sohu.com/us/63335670/61135536.shtml'),trim('姚贝娜为何爆冷出局[每日文娱播报]-原创视频-搜狐视频'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-10-14',trim('  拍摄“广汽丰田”广告'),trim('  拍摄“广汽丰田”广告（貌似会出mv，待补充）  '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-10-16',trim(' 做客搜狐客户端自媒体直播间'),trim(' 做客搜狐客户端自媒体直播间 搜狐客户端发言'));
insert into bellawiki_file (`url`,`name`) values (trim('http://www.tudou.com/programs/view/PE6OS-AUgho/?resourceId=0_06_02_99'),trim('姚贝娜搜狐客户端发言'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-10-17',trim(' 搜狐视频专访'),trim(' 搜狐视频专访姚贝娜：中国好声音独家猛料 姚贝娜披露化疗期间心路历程 回应黑幕质疑'));
insert into bellawiki_file (`url`,`name`) values (trim('http://tv.sohu.com/20131017/n388353040.shtml/?pvid=df93a5bacf00568a'),trim('《中国好声音第二季独家猛料》姚贝娜披露化疗期间心路历程 回应黑幕质疑 '));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-10-17',trim(' 北京雅诗兰黛集团“粉红丝带乳腺健康粉皮书”新闻发布会     '),trim(' 北京雅诗兰黛集团“粉红丝带乳腺健康粉皮书”新闻发布会     '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-10-17',trim(' 搜狐视频好声音庆功会'),trim(' 搜狐视频好声音庆功会《dear friend》'));
insert into bellawiki_file (`url`,`name`) values (trim('http://www.iqiyi.com/common/qplay.html?tvid=799792&vid=177b6fc9eb20426aba089baf02c858fe&cnid=23?source='),trim('error'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-10-18',trim(' 拍摄VOGUE杂志记录'),trim(' 拍摄VOGUE杂志记录：姚贝娜钟爱裤衩背心休闲风 自曝从小爱臭美'));
insert into bellawiki_file (`url`,`name`) values (trim('http://tv.sohu.com/20131018/n388474598.shtml'),trim('《中国好声音第二季视频报道》姚贝娜钟爱裤衩背心休闲风 自曝从小爱臭美 '));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-10-19',trim(' 温州瑞安五星国际商贸城开幕'),trim(' 温州瑞安五星国际商贸城开幕'));
insert into bellawiki_file (`url`,`name`) values (trim('http://v.youku.com/v_show/id_XNjIzNDM4MDA0.html'),trim('姚贝娜 瑞安商演视频'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-10-20',trim(' 浙江卫视我爱记歌词'),trim(' 浙江卫视我爱记歌词'));
insert into bellawiki_file (`url`,`name`) values (trim('http://www.iqiyi.com/v_19rrh8o03k.html'),trim('我爱记歌词20131020姚贝娜爱忘词'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-10-20',trim(' 《爱无反顾》MV发布'),trim(' 《爱无反顾》MV发布'));
insert into bellawiki_file (`url`,`name`) values (trim('http://v.yinyuetai.com/video/792373'),trim('【MV】姚贝娜'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-10-20',trim(' 大好河山我的梦●2013张家口金秋音乐盛典'),trim(' 大好河山我的梦●2013张家口金秋音乐盛典'));
insert into bellawiki_file (`url`,`name`) values (trim('http://v.youku.com/v_show/id_XNjI0NDcwMTky.html'),trim('20131020张家口演唱会-姚贝娜《红颜劫》《也许在》《我要的很简单》《也许明天》'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-10-21',trim('  永康国际会展中心《超人集团30周年盛典晚会》'),trim('  永康国际会展中心《超人集团30周年盛典晚会》'));
insert into bellawiki_file (`url`,`name`) values (trim('http://v.youku.com/v_show/id_XNjI0ODc5MTI4.html'),trim('姚贝娜  永康国际会展中心  '));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-10-25',trim(' 昆明俊发商业品牌起航暨滨江·俊发广场商家签约仪式'),trim(' 昆明俊发商业品牌起航暨滨江·俊发广场商家签约仪式'));
insert into bellawiki_file (`url`,`name`) values (trim('http://v.youku.com/v_show/id_XNjI2MzQ5NTcy.html'),trim('10.25姚贝娜昆明商演签约'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-10-26',trim('.广州萝岗万达好声音演唱会'),trim('.广州萝岗万达好声音演唱会'));
insert into bellawiki_file (`url`,`name`) values (trim('http://v.youku.com/v_show/id_XNjI2OTg4OTg0.html'),trim('姚贝娜广州箩岗演艺中心'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-10-28',trim(' 中国好声音杭州十六强演唱会'),trim(' 中国好声音杭州十六强演唱会姚贝娜VS侯磊 《也许在》'));
insert into bellawiki_file (`url`,`name`) values (trim('http://v.youku.com/v_show/id_XNjI3NTU5MzUy.html'),trim('《也许在》 - 姚贝娜、候磊（杭州站 2013.10.28）'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-11-2',trim(' 江苏昆山“好声音白鹭湾之夜”'),trim(' 江苏昆山“好声音白鹭湾之夜”红颜劫 http://v.youku.com/v_show/id_XNjMwMDU4NzAw.html我要的很简单 http://v.youku.com/v_show/id_XNjMwMDkxNjc2.html也许明天 http://v.youku.com/v_show/id_XNjMwMTE4MzY0.html     '));
insert into bellawiki_file (`url`,`name`) values (trim('http://v.youku.com/v_show/id_XNjMwMDU4NzAw.html'),trim('昆山-红颜劫'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into bellawiki_file (`url`,`name`) values (trim('http://v.youku.com/v_show/id_XNjMwMDkxNjc2.html'),trim('昆山-我要的很简单 '));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into bellawiki_file (`url`,`name`) values (trim('http://v.youku.com/v_show/id_XNjMwMTE4MzY0.html     '),trim('昆山-也许明天'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-11-5',trim('宾利深圳与深业上城酒会青藏高原'),trim('   宾利深圳与深业上城酒会青藏高原 http://papa.me/post/HA8pH6l3?syncref=sinapost     '));
insert into bellawiki_file (`url`,`name`) values (trim('http://papa.me/post/HA8pH6l3?syncref=sinapost'),trim('"西瓜晶的第二人生 - 啪啪图片声音社区"'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-11-5',trim('姚如意视频记忆2006-2013'),trim('强烈推荐个视频，一定要看姚如意视频记忆2006-2013'));
insert into bellawiki_file (`url`,`name`) values (trim('http://www.tudou.com/programs/view/VeD4sTunhcU/?resourceId=31463179_06_02_99'),trim('姚如意视频记忆2006-2013'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-11-6',trim('上海战争世界发布会'),trim('  上海战争世界发布会，演唱主题曲专访《战争世界》主题曲演唱者-姚贝娜    '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-11-8',trim('苏州首届五金博览会演唱会'),trim('   苏州首届五金博览会演唱会'));
insert into bellawiki_file (`url`,`name`) values (trim('http://v.youku.com/v_show/id_XNjMyNjU0MjI4.html'),trim('姚贝娜-苏州首届五金博览会演唱会全场1080P'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-11-9',trim(' 好声音百城百场演唱会北京站'),trim(' 好声音百城百场演唱会北京站http://music.letv.com/zt/thevoiceofchina/index.shtml   '));
insert into bellawiki_file (`url`,`name`) values (trim('http://music.letv.com/zt/thevoiceofchina/index.shtml'),trim('第二季中国好声音全国巡演_高清直播间_视频回放_专题_乐视网'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-11-10',trim(' 好声音巡演石家庄站好声音石家庄演唱会'),trim(' 好声音巡演石家庄站好声音石家庄演唱会全程视频第二段《红颜劫》《也许明天》'));
insert into bellawiki_file (`url`,`name`) values (trim('http://v.youku.com/v_show/id_XNjMzMzY3NTE2.html'),trim('好声音石家庄演唱会全程视频第二段《红颜劫》《也许明天》'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-11-11',trim(' YOKA独家专访姚贝娜'),trim(' YOKA独家专访姚贝娜'));
insert into bellawiki_file (`url`,`name`) values (trim('http://v.youku.com/v_show/id_XNjMzMjgyNDc2.html'),trim('YOKA独家专访姚贝娜'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-11-11',trim(' 新闻联播报道姚贝娜上春晚片段'),trim(' 新闻联播报道姚贝娜上春晚片段'));
insert into bellawiki_file (`url`,`name`) values (trim('http://www.tudou.com/programs/view/adMrwEkLdNI/'),trim('姚贝娜新闻'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-11-11',trim('姚峰、刘罡，姚贝娜武音演唱会'),trim(' 也许明天---姚峰、刘罡，姚贝娜武音演唱会【视频】【湖北后援会】11.11娜娜武音现场视频清晰版 http://tieba.baidu.com/p/2702294836【爱无反顾】武音演唱会现场视频清晰版列表（有亮点哦） http://tieba.baidu.com/p/2702198449?share=9105【爱无反顾】武音姚贝儿视频集合 http://tieba.baidu.com/p/2700896208（出官方版再补充）      '));
insert into bellawiki_file (`url`,`name`) values (trim('http://tieba.baidu.com/p/2702294836'),trim('【视频】【湖北后援会】11.11娜娜武音现场视频清晰版'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-11-11',trim('ELLE中文网独家专访姚贝娜：破茧成蝶的惊艳'),trim('插一条新闻【新闻】ELLE中文网独家专访姚贝娜：破茧成蝶的惊艳 http://tieba.baidu.com/p/2701226994（对很多大家关心的问题作出了解释，很有价值） '));
insert into bellawiki_file (`url`,`name`) values (trim('http://tieba.baidu.com/p/2701226994'),trim('【新闻】ELLE中文网独家专访姚贝娜：破茧成蝶的惊艳'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-11-15',trim(' 好声音巡演泸州站'),trim(' 好声音巡演泸州站目前只找到红颜劫，待补充'));
insert into bellawiki_file (`url`,`name`) values (trim('http://v.youku.com/v_show/id_XNjM1MzI4NjI4.html'),trim('姚贝娜'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-11-16',trim(' 好声音巡演济南站'),trim(' 好声音巡演济南站也许在 http://v.youku.com/v_show/id_XNjM1NjUyMDI4.html也许明天 http://v.youku.com/v_show/id_XNjM1NjY2MTUy.html    '));
insert into bellawiki_file (`url`,`name`) values (trim('http://v.youku.com/v_show/id_XNjM1NjUyMDI4.html'),trim('《也许在》姚贝娜、候磊 （济南站 2013-11-16）'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-11-18',trim(' 2013女性传媒大奖网易女人专访姚贝娜'),trim(' 2013女性传媒大奖网易女人专访姚贝娜'));
insert into bellawiki_file (`url`,`name`) values (trim('http://v.youku.com/v_show/id_XNjM2MzA0NzQ4.html'),trim('网易女人专访姚贝娜'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-11-17',trim(' 《西安偶像》特别节目姚贝娜'),trim(' 《西安偶像》特别节目姚贝娜'));
insert into bellawiki_file (`url`,`name`) values (trim('http://www.tudou.com/programs/view/8z11pLgqfy4/?resourceId=0_06_02_99'),trim('西安偶像225好声音特别节目（姚贝娜）'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-11-20',trim(' 广汽丰田致炫价格发布会'),trim(' 广汽丰田致炫价格发布会现场演唱《也许明天》    '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-11-21',trim(' 北京果味VC新专辑发布会果味VC发新专辑'),trim(' 北京果味VC新专辑发布会果味VC发新专辑 粉丝姚贝娜送礼祝贺 '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-11-22',trim(' 好声音巡演泰州站'),trim(' 好声音巡演泰州站     '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-11-22',trim(' 我要上春晚《Bring me to life》'),trim(' 我要上春晚《Bring me to life》（录制于2013.6.16）'));
insert into bellawiki_file (`url`,`name`) values (trim('http://v.youku.com/v_show/id_XNjM4Mzc2NzQw.html'),trim('姚贝娜-bring me to life'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-11-23',trim(' 《我们一家人》主题曲《诺言》首播'),trim(' 《我们一家人》主题曲《诺言》首播姚贝娜~诺言.mp3 http://pan.baidu.com/share/link?shareid=579255444&uk=859009648  '));
insert into bellawiki_file (`url`,`name`) values (trim('http://pan.baidu.com/share/link?shareid=579255444&uk=859009648'),trim('姚贝娜~诺言.mp3_免费高速下载|百度云 网盘-分享无限制'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-11-23',trim(' 重庆长江国际原墅开放仪式也许明天'),trim(' 重庆长江国际原墅开放仪式也许明天'));
insert into bellawiki_file (`url`,`name`) values (trim('http://v.youku.com/v_show/id_XNjM4ODIyMDc2.html'),trim('2013.11.23姚贝娜重庆巴南长江国际原墅商演'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-11-24',trim('  贵州•兴义浙兴商贸博览城之夜 中国好声音群星演唱会'),trim('  贵州•兴义 浙兴商贸博览城之夜 中国好声音群星演唱会'));
insert into bellawiki_file (`url`,`name`) values (trim('http://v.pps.tv/play_39Z4WR.html'),trim('中国好声音学员 姚贝娜'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-11-24',trim(' 姚贝娜 现场清唱集锦'),trim(' 推荐：姚贝娜 现场清唱集锦'));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-11-24',trim(' 姚贝娜-心火-MV-饥饿游戏版'),trim(' 推荐：姚贝娜-心火-MV-饥饿游戏版'));
insert into bellawiki_file (`url`,`name`) values (trim('http://v.youku.com/v_show/id_XNjM5MDQzNzQ4.html'),trim('姚贝娜-心火-MV-饥饿游戏版'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-11-27',trim(' 南京溧水 “悦动全城 星耀五洲”群星演唱会《红颜劫》'),trim(' 南京溧水 “悦动全城 星耀五洲”群星演唱会《红颜劫》'));
insert into bellawiki_file (`url`,`name`) values (trim('http://v.youku.com/v_show/id_XNjQxNDgxNDQ0.html'),trim('2013-11-27 姚贝娜 溧水演唱红颜劫'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-11-28',trim(' 全新单曲《不唱情歌》首发不唱情歌 - 姚贝娜   '),trim(' 全新单曲《不唱情歌》首发不唱情歌 - 姚贝娜   '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-11-28',trim(' 南通中谨.翰伯府演唱会《也许明天》'),trim(' 南通中谨.翰伯府演唱会《也许明天》'));
insert into bellawiki_file (`url`,`name`) values (trim('http://v.youku.com/v_show/id_XNjQxMTAyODY0.html'),trim('中瑾 姚贝娜。'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-11-29',trim(' 北京“Dear Friend—网信之夜”超凡精英聚会'),trim(' 北京“Dear Friend—网信之夜”超凡精英聚会【图片】11.29 网信之夜超凡精英聚会 姚贝儿微博图 http://tieba.baidu.com/p/2732966265?pid=42339322426&cid=#42339322426     '));
insert into bellawiki_file (`url`,`name`) values (trim('http://tieba.baidu.com/p/2732966265?pid=42339322426&cid=#42339322426'),trim('【图片】11.29  网信之夜超凡精英聚会 姚贝儿微博图'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-11-30',trim(' 四川乐山好声音海天夜'),trim(' 四川乐山好声音海天夜'));
insert into bellawiki_file (`url`,`name`) values (trim('http://v.youku.com/v_show/id_XNjQyMTk4MjQw.html'),trim('姚贝娜 乐山演出2013.11.30'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-12-3',trim(' 北京 姚贝娜EP《1/2的我》发布会'),trim(' 北京 姚贝娜EP《1/2的我》发布会'));
insert into bellawiki_file (`url`,`name`) values (trim('http://v.yinyuetai.com/video/825913'),trim('<1/2的我>新碟发布会'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-12-4',trim(' MusicRadio巨星梦想会客室专访姚贝娜'),trim(' MusicRadio巨星梦想会客室专访姚贝娜【1/2的我】music radio录音 http://tieba.baidu.com/p/2742050985  '));
insert into bellawiki_file (`url`,`name`) values (trim('http://tieba.baidu.com/p/2742050985'),trim('【1/2的我】music radio录音'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-12-9',trim(' 姚贝娜全新EP《1/2的我》首发'),trim(' 姚贝娜全新EP《1/2的我》首发战争世界 - 姚贝娜爱无反顾 - 姚贝娜不唱情歌 - 姚贝娜心火 - 姚贝娜  '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-12-11',trim(' 网易云音乐《明星会客室》专访'),trim(' 网易云音乐《明星会客室》专访姚贝娜：独家讲述“二分之一的我”http://music.163.com/#/m/dj?id=632370      '));
insert into bellawiki_file (`url`,`name`) values (trim('http://music.163.com/#/m/dj?id=632370'),trim('网易云音乐 听见好时光'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-12-14',trim(' 好声音巡演深圳站'),trim(' 好声音巡演深圳站'));
insert into bellawiki_file (`url`,`name`) values (trim('http://www.tudou.com/programs/view/EbVUZRybiAk/?resourceId=107217851_06_02_99'),trim('2013.12.14 姚贝娜《也许在》《Dear Friend》'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-12-17',trim(' 出席电影《私人定制》首映礼      '),trim(' 出席电影《私人定制》首映礼      '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-12-17',trim(' 北京五棵松京东校园之星总决赛'),trim(' 北京五棵松京东校园之星总决赛【1/2的我】——视频——京东校园之星《不唱情歌》《也许明天》 http://tieba.baidu.com/p/2765912845    '));
insert into bellawiki_file (`url`,`name`) values (trim('http://tieba.baidu.com/p/2765912845'),trim('【1/2的我】——视频——京东校园之星《不唱情歌》《也许明天》'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-12-18',trim(' 2013国剧盛典观众最喜爱的影视歌演唱人    '),trim('  2013国剧盛典观众最喜爱的影视歌演唱人    '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-12-19',trim(' 腾讯2013年度微盛典最具人气女歌手      '),trim('  腾讯2013年度微盛典最具人气女歌手      '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-12-20',trim(' 武汉万达电影乐园&汉秀开幕倒计时365天启动仪式 '),trim(' 武汉万达电影乐园&汉秀开幕倒计时365天启动仪式 '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-12-20',trim(' 哈尔滨维雪啤酒好声音信阳演唱会    '),trim(' 哈尔滨维雪啤酒好声音信阳演唱会    '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-12-21',trim(' 云南芒市拍摄《彩虹之恋》宣传片    '),trim(' 云南芒市拍摄《彩虹之恋》宣传片    '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-12-22',trim(' 共筑和谐社会，实现中国梦想—“大德至信，大爱无垠”关爱老人慈善联谊会  '),trim('  共筑和谐社会，实现中国梦想—“大德至信，大爱无垠”关爱老人慈善联谊会  '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-12-22',trim(' 录制湖北卫视2014新年环球狂欢夜'),trim(' 录制湖北卫视2014新年环球狂欢夜（2014.1.1 湖北卫视播出）   '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-12-23',trim(' 深圳华昱机构年会'),trim(' 深圳华昱机构年会     '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-12-27',trim(' 陕西汉中堂宏广场之夜港台明星大型演唱会'),trim(' 陕西汉中堂宏广场之夜港台明星大型演唱会      '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2013-12-30',trim(' 2013国剧盛典观众最喜爱的影视歌演唱人'),trim('  2013国剧盛典观众最喜爱的影视歌演唱人（录制于12.18）      '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-1-1',trim(' 湖北卫视新年环球狂欢夜'),trim(' 湖北卫视新年环球狂欢夜（录制于2013.12.22）      '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-1-5',trim(' 凤凰视频年终策划《我》'),trim('  凤凰视频年终策划《我》 姚贝娜'));
insert into bellawiki_file (`url`,`name`) values (trim('http://v.ifeng.com/program/special/2014001/01db88a7-5718-47cd-8fc6-06e0883fbcc1.shtml'),trim('2014-01-05凤凰视频年终策划《我》姚贝娜-20140105凤凰视频年终策划《我》'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-1-6',trim(' 电影《前任攻略》主题曲《矜持》发布'),trim(' 电影《前任攻略》主题曲《矜持》发布http://y.qq.com/#type=song&mid=000fGbWu2BXxkh      '));
insert into bellawiki_file (`url`,`name`) values (trim('http://y.qq.com/#type=song&mid=000fGbWu2BXxkh'),trim('QQ音乐-音乐你的生活！'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-1-6',trim(' 网易旅游2013年终策划-专访姚贝娜'),trim(' 网易旅游2013年终策划-专访姚贝娜http://v.travel.163.com/video/2014/1/3/0/V9GLNHO30.html '));
insert into bellawiki_file (`url`,`name`) values (trim('http://v.travel.163.com/video/2014/1/3/0/V9GLNHO30.html'),trim('网易旅游2013年终策划-专访姚贝娜 - 网易旅游视频'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-1-6',trim(' 第二届搜狐时尚权力榜颁奖盛典'),trim(' 第二届搜狐时尚权力榜颁奖盛典http://fashion.sohu.com/s2014/fashionawards2014/index.shtml（45分钟左右）     '));
insert into bellawiki_file (`url`,`name`) values (trim('http://fashion.sohu.com/s2014/fashionawards2014/index.shtml'),trim('第二届搜狐时尚盛典直播专题-搜狐'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-1-7',trim(' 姚贝娜做客《东方风云榜》动感101'),trim(' 姚贝娜做客《东方风云榜》动感101'));
insert into bellawiki_file (`url`,`name`) values (trim('http://www.tudou.com/programs/view/dY1-xHfLB0w/'),trim('20140107姚贝娜做客《东方风云榜》动感101'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-1-8',trim(' 姚贝娜做客iRadio大来宾'),trim(' 姚贝娜做客iRadio大来宾'));
insert into bellawiki_file (`url`,`name`) values (trim('http://www.tudou.com/programs/view/uksmlr5LpSM/'),trim('20140108姚贝娜做客iRadio大来宾'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-1-9',trim(' 新浪年度车2014颁奖典礼'),trim(' 新浪年度车2014颁奖典礼http://auto.sina.com.cn/video/2014-01-10/000963357389.html?bsh_bid=337424428   '));
insert into bellawiki_file (`url`,`name`) values (trim('http://auto.sina.com.cn/video/2014-01-10/000963357389.html?bsh_bid=337424428'),trim('视频:中国好声音学员姚贝娜献唱也许明天_新浪汽车_新浪网'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-1-12',trim(' 天津南洋胡氏二十周年庆典 '),trim(' 天津南洋胡氏二十周年庆典 '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-1-13',trim(' CCTV3《我要上春晚》年终总决赛第二场     '),trim(' CCTV3《我要上春晚》年终总决赛第二场     '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-1-15',trim(' 电影《前任攻略》新闻发布会      '),trim(' 电影《前任攻略》新闻发布会      '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-1-15',trim(' 微博之夜获微博年度人气奖 '),trim(' 微博之夜获微博年度人气奖 '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-1-16',trim(' 温州瑞安香缇花园开盘倒计时      '),trim(' 温州瑞安香缇花园开盘倒计时      '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-1-18',trim(' 淮海第一城-新天地落成庆典      '),trim(' 淮海第一城-新天地落成庆典      '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-1-19',trim(' 做客《京东会客厅》    '),trim(' 做客《京东会客厅》    '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-1-21',trim(' 与梦同行 日照兴业集团2014年春节联欢晚会   '),trim(' 与梦同行 日照兴业集团2014年春节联欢晚会   '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-1-22',trim(' 做客西华师范大学新传之声网络电台'),trim(' 做客西华师范大学新传之声网络电台'));
insert into bellawiki_file (`url`,`name`) values (trim('http://www.tudou.com/programs/view/3DMJiM1Jgds/?resourceId=0_06_02_99'),trim('西华师大新传之声网络电台和蜻蜓FM联合制作“姚贝娜专访”'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-1-23',trim(' 《中国访谈》姚贝娜：执着梦想 善待生活'),trim(' 《中国访谈》姚贝娜：执着梦想 善待生活http://www.china.com.cn/fangtan/node_7198746.htm      '));
insert into bellawiki_file (`url`,`name`) values (trim('http://www.china.com.cn/fangtan/node_7198746.htm'),trim('姚贝娜专访_中国访谈_中国网'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-1-23',trim(' 武汉华氏集团20周年庆典暨2013年年度人物颁奖盛典     '),trim(' 武汉华氏集团20周年庆典暨2013年年度人物颁奖盛典     '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-1-24',trim(' 姚贝娜做客新浪聊春晚   '),trim(' 姚贝娜做客新浪聊春晚   '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-1-24',trim(' 慧聪网年会  '),trim(' 慧聪网年会  '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-1-25',trim(' 上海新娱乐《陈蓉博客》之姚贝娜 唱出好声音'),trim(' 上海新娱乐《陈蓉博客》之姚贝娜 唱出好声音'));
insert into bellawiki_file (`url`,`name`) values (trim('http://www.iqiyi.com/v_19rrgzlrp0.html?share_sTime=0-share_eTime=1240'),trim('陈蓉博客20140125'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-1-28',trim(' #女神伴你回家路#姚贝娜作客搜狐新闻客户端直播间'),trim(' #女神伴你回家路#姚贝娜作客搜狐新闻客户端直播间 聊聊参加春晚这些年   '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-1-30',trim(' 2014央视马年春晚 '),trim(' 2014央视马年春晚 '));
insert into bellawiki_file (`url`,`name`) values (trim('http://www.iqiyi.com/v_19rrgyprrg.html'),trim('央视2014春晚20140130姚贝娜《天耀中华》'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-1-31',trim(' 北京卫视2014春晚'),trim(' 北京卫视2014春晚     《心火》'));
insert into bellawiki_file (`url`,`name`) values (trim('http://www.iqiyi.com/v_19rrgyqh0s.html'),trim('北京卫视2014春晚20140131姚贝娜《心火》'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-2-19',trim('做客《京东会客厅》'),trim('（录制于1.19） 做客《京东会客厅》http://jd.yuntv.letv.com/play/626.html     '));
insert into bellawiki_file (`url`,`name`) values (trim('http://jd.yuntv.letv.com/play/626.html'),trim('做客《京东会客厅》'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-2-25',trim(' 《朝闻天下》 艺考故事：小样歌手姚贝娜      '),trim(' 《朝闻天下》 艺考故事：小样歌手姚贝娜      '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-2-28',trim(' 唱响东兴群星演唱会    '),trim(' 唱响东兴群星演唱会    '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-3-1',trim('  音乐电影《彩云之恋》 CCTV6《美丽中国·音乐电影欣赏》首播      '),trim('  音乐电影《彩云之恋》 CCTV6《美丽中国·音乐电影欣赏》首播      '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-3-5',trim(' Music Radio中国TOP排行榜颁奖典礼启动仪式     '),trim(' Music Radio中国TOP排行榜颁奖典礼启动仪式     '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-3-10',trim(' MusicRadio音乐之声《音乐VIP》第一期：做自己'),trim(' MusicRadio音乐之声《音乐VIP》第一期：做自己'));
insert into bellawiki_file (`url`,`name`) values (trim('http://www.tudou.com/programs/view/MTRbOjg7DiM/'),trim('20140310音乐之声《音乐VIP》姚贝娜（第一期）'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-3-11',trim(' 真维斯&搜狐视频战略合作发布会    '),trim(' 真维斯&搜狐视频战略合作发布会    '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-3-4',trim(' 《后海星光下之LIFE VIP》妇女节特别呈现《@姚贝娜  的那些人 那些事》'),trim(' 《后海星光下之LIFE VIP》妇女节特别呈现《@姚贝娜  的那些人 那些事》'));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-3-3',trim(' 讲诉在好声音上的故事'),trim(' 讲诉在好声音上的故事 http://www.tudou.com/programs/view/iudC0VC1fuk/ '));
insert into bellawiki_file (`url`,`name`) values (trim('http://www.tudou.com/programs/view/iudC0VC1fuk/ '),trim(' 讲诉在好声音上的故事'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-3-4',trim(' 面对伤痛和病痛时鲜为人知的小故事'),trim(' 面对伤痛和病痛时鲜为人知的小故事 http://www.tudou.com/programs/view/P4YEJmentr8/ '));
insert into bellawiki_file (`url`,`name`) values (trim('http://www.tudou.com/programs/view/P4YEJmentr8/ '),trim(' 面对伤痛和病痛时鲜为人知的小故事'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-3-5',trim(' 姚贝娜和她的爱情故事'),trim(' 姚贝娜和她的爱情故事 http://www.tudou.com/programs/view/Xbi9AMKiPuk/ '));
insert into bellawiki_file (`url`,`name`) values (trim('http://www.tudou.com/programs/view/Xbi9AMKiPuk/ '),trim(' 姚贝娜和她的爱情故事'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-3-6',trim(' 姚贝首度开腔谈自己的爱情世界'),trim(' 姚贝首度开腔谈自己的爱情世界 http://www.tudou.com/programs/view/FYRT9chERUs/ '));
insert into bellawiki_file (`url`,`name`) values (trim('http://www.tudou.com/programs/view/FYRT9chERUs/ '),trim(' 姚贝首度开腔谈自己的爱情世界'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-3-7',trim(' 姚贝谈谈自己梦想'),trim(' 姚贝谈谈自己梦想 http://www.tudou.com/programs/view/W_9PRsTomog/      '));
insert into bellawiki_file (`url`,`name`) values (trim('http://www.tudou.com/programs/view/W_9PRsTomog/      '),trim(' 姚贝谈谈自己梦想'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-3-13',trim(' MusicRadio中国TOP排行榜沈阳活力拉票会      '),trim(' MusicRadio中国TOP排行榜沈阳活力拉票会      '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-3-20',trim(' CCTV-6《音乐之声》特别策划：聚焦“灵魂歌者”姚贝娜'),trim(' CCTV-6《音乐之声》特别策划：聚焦“灵魂歌者”姚贝娜 《红颜劫》中惊艳亮相    '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-3-23',trim(' 《我上春晚了》      '),trim(' 《我上春晚了》      '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-3-27',trim(' 镇江 “三山”景区旅游推介会'),trim(' 镇江 “三山”景区旅游推介会在北京举行 签约为“三山”景区形象代言人   '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-3-28',trim(' 2014《型男志Men’s JOKER》男士理容大典     '),trim(' 2014《型男志Men’s JOKER》男士理容大典     '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-3-29',trim(' 湖北汉川 汉海好声音之夜 '),trim(' 湖北汉川 汉海好声音之夜 '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-3-30',trim(' CCTV3《我上春晚了 下》     '),trim(' CCTV3《我上春晚了 下》     '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-3-31',trim('  《Beautiful Light》MV'),trim('  《Beautiful Light》MV'));
insert into bellawiki_file (`url`,`name`) values (trim('http://www.tudou.com/programs/view/11zJy6A2QF0/'),trim('《Beautiful Light》不一样的色彩：姚贝娜白色版演绎“包容”主题'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-4-3',trim(' 万达集团的南昌万达茂奠基盛典      '),trim(' 万达集团的南昌万达茂奠基盛典      '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-4-10',trim(' 成都城市之音十周年记者会 '),trim(' 成都城市之音十周年记者会 '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-4-12',trim(' 全球中文音乐榜上榜    '),trim(' 全球中文音乐榜上榜    '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-4-13',trim(' 奥克斯空调20周年庆典  '),trim(' 奥克斯空调20周年庆典  '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-4-15',trim(' 2014爱的小桔灯新闻发布会     '),trim(' 2014爱的小桔灯新闻发布会     '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-4-17',trim(' 姚贝娜做客《乐视star》'),trim(' 姚贝娜做客《乐视star》http://ent.letv.com/zt/star/index.shtml?ref=index_focus_7   '));
insert into bellawiki_file (`url`,`name`) values (trim('http://ent.letv.com/zt/star/index.shtml?ref=index_focus_7'),trim('star_star明星访谈_明星访谈直播_专题_乐视网'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-4-18',trim(' MR网络金曲演唱会'),trim(' MR网络金曲演唱会'));
insert into bellawiki_file (`url`,`name`) values (trim('http://v.youku.com/v_show/id_XNzAxMDIyODY0.html'),trim('2014418MR金曲网络演唱会姚贝娜全程'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-4-19',trim('  七彩致炫·七城试驾武汉站      '),trim('  七彩致炫·七城试驾武汉站      '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-4-21',trim(' 京东“东乐计划”媒体发布会      '),trim(' 京东“东乐计划”媒体发布会      '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-4-26',trim(' 2013年度蒙牛酸酸乳MusicRadio中国TOP排行榜颁奖晚会    '),trim(' 2013年度蒙牛酸酸乳MusicRadio中国TOP排行榜颁奖晚会    '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-4-27',trim(' 北京爱琴海购物中心《1/2 的我》签售会     '),trim(' 北京爱琴海购物中心《1/2 的我》签售会     '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-4-28',trim(' 大型水景秀《白蛇传》首演 '),trim(' 大型水景秀《白蛇传》首演 '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-4-29',trim(' 郑州签唱会  '),trim(' 郑州签唱会  '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-5-1',trim(' 辽宁卫视中国《喜剧力量》助唱嘉宾录制  '),trim(' 辽宁卫视中国《喜剧力量》助唱嘉宾录制  '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-5-2',trim(' 中航城-大美上饶群星演唱会 '),trim(' 中航城-大美上饶群星演唱会 '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-5-6',trim(' MusicRadio音乐之声HIGH歌校园行首场北京站暨启动仪式      '),trim(' MusicRadio音乐之声HIGH歌校园行首场北京站暨启动仪式      '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-5-8',trim(' 风尚加州Calibio VIP分享会  '),trim(' 风尚加州Calibio VIP分享会  '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-5-11',trim(' 合肥签唱会  '),trim(' 合肥签唱会  '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-5-15',trim(' CCTV-3《艺术人生》姚贝娜专辑  '),trim(' CCTV-3《艺术人生》姚贝娜专辑  '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-5-17',trim(' 中国新歌榜首届颁奖典礼  '),trim(' 中国新歌榜首届颁奖典礼  '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-5-18',trim(' 做客中国之声《中国大舞台》      '),trim(' 做客中国之声《中国大舞台》      '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-5-24',trim(' 助阵湖北好声音晋级赛   '),trim(' 助阵湖北好声音晋级赛   '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-5-30',trim(' 2014香港青年音乐节  '),trim(' 2014香港青年音乐节  '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-6-1',trim(' 2014年“六一”晚会《在五彩缤纷的节日里》    '),trim(' 2014年“六一”晚会《在五彩缤纷的节日里》    '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-6-7',trim(' 华谊兄弟20周年庆典    '),trim(' 华谊兄弟20周年庆典    '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-6-9',trim(' 搜狐视频《世界杯特别报道》开播仪式   '),trim(' 搜狐视频《世界杯特别报道》开播仪式   '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-6-17',trim(' 做客《黄焖世界杯》第5期 '),trim(' 做客《黄焖世界杯》第5期 '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-6-14',trim(' 泰州海之蓝群星演唱会   '),trim(' 泰州海之蓝群星演唱会   '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-6-21',trim(' 城市至尊音乐盛典     '),trim(' 城市至尊音乐盛典     '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-6-15',trim(' 2014华谊ELLE之夜 '),trim(' 2014华谊ELLE之夜 '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-6-25',trim(' 爱是最美的风尚明星盛典  '),trim(' 爱是最美的风尚明星盛典  '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-6-28',trim(' 星耀潮白河演唱会     '),trim(' 星耀潮白河演唱会     '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-6-29',trim(' 星河集团25周年品牌战略发布会    '),trim(' 星河集团25周年品牌战略发布会    '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-6-30',trim(' 《我不是明星》      '),trim(' 《我不是明星》      '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-7-7',trim(' 百度乐播《世界杯星播客》：姚贝娜带你了解C罗与小贝的不同    '),trim(' 百度乐播《世界杯星播客》：姚贝娜带你了解C罗与小贝的不同    '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-7-15',trim(' 明星说公益之姚贝娜    '),trim(' 明星说公益之姚贝娜    '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-8-7',trim(' 辽宁卫视《中国喜剧力量》  '),trim(' 辽宁卫视《中国喜剧力量》  '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-8-8',trim(' 正荣润璟产品发布会     '),trim(' 正荣润璟产品发布会     '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-8-17',trim(' 石狮“泰禾之夜”     '),trim(' 石狮“泰禾之夜”     '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-8-27',trim(' 齐齐哈尔 北大仓百年庆演出      '),trim(' 齐齐哈尔 北大仓百年庆演出      '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-8-22',trim('兰蔻法式轻妆潮第二任轻妆大使-姚贝娜'),trim(' 视频：兰蔻法式轻妆潮第二任轻妆大使-姚贝娜http://v.youku.com/v_show/id_XNzU5NzAyNTAw.html     '));
insert into bellawiki_file (`url`,`name`) values (trim('http://v.youku.com/v_show/id_XNzU5NzAyNTAw.html'),trim('兰蔻法式轻妆潮第二任轻妆使者-姚贝娜'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-9-17',trim(' 《为梦想放歌——第十三届精神文明建设“五个一工程”获奖作品专题节目》'),trim(' 《为梦想放歌——第十三届精神文明建设“五个一工程”获奖作品专题节目》'));
insert into bellawiki_file (`url`,`name`) values (trim('http://www.tudou.com/programs/view/wPnOCJiuddE/'),trim('140917姚贝娜《时间都去哪儿了》.HDTV.1080i.MPEG2-CHDTV.ts'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-9-20',trim(' 中国传媒大学60周年校庆《随他吧》'),trim(' 中国传媒大学60周年校庆《随他吧》'));
insert into bellawiki_file (`url`,`name`) values (trim('http://v.youku.com/v_show/id_XNzg2OTg0NjUy.html'),trim('20140920中国传媒大学60周年校庆-姚贝娜《随它吧》'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-9-21',trim(' 西安万科草坪音乐节'),trim(' 西安万科草坪音乐节'));
insert into bellawiki_file (`url`,`name`) values (trim('http://www.56.com/u55/v_MTI1NTk3NTE2.html'),trim('姚贝娜9.21西安万科现场演出视频_视频在线观看 - 56.com'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-9-28',trim(' 屈臣氏蒸馏水「爱·动情歌」上海演唱会'),trim(' 屈臣氏蒸馏水「爱·动情歌」上海演唱会'));
insert into bellawiki_file (`url`,`name`) values (trim('http://v.youku.com/v_show/id_XNzkzMTc4OTMy.html'),trim('屈臣氏《爱动情歌》上海站 姚贝娜1'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-10-1',trim('CCTV-3《我和我的祖国》特别节目'),trim('CCTV-3《我和我的祖国》特别节目'));
insert into bellawiki_file (`url`,`name`) values (trim('http://v.youku.com/v_show/id_XNzk0NzU1OTQ0.html'),trim('20141001《我和我的祖国》-姚贝娜'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-10-10',trim(' 第十届中国电视金鹰节开幕式'),trim(' 第十届中国电视金鹰节开幕式 刘欢&姚贝娜《天地在我心》'));
insert into bellawiki_file (`url`,`name`) values (trim('http://v.youku.com/v_show/id_XODAwNzk3Njg4.html'),trim('《天地在我心》刘欢 姚贝娜 18—在线播放—《第十届金鹰节开幕式》—综艺'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-10-9',trim(' 山西农业大学信息学院第二届校园音乐节开幕式暨2014迎新晚会 '),trim(' 山西农业大学信息学院第二届校园音乐节开幕式暨2014迎新晚会 '));
insert into bellawiki_file (`url`,`name`) values (trim('http://v.youku.com/v_show/id_XODAwNjA1NDIw.html'),trim('141009 姚贝娜 山西农大信院全程'));
insert into bellawiki_work_files (`work_id`, `file_id`) values ((select max(id) from bellawiki_work),(select max(id) from bellawiki_file));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-10-18',trim(' 广汽丰田十周年纪念晚会《一路有你》 '),trim(' 广汽丰田十周年纪念晚会《一路有你》 '));
insert into belliwiki_work (`date`,`title`,`desc`) values ('2014-11-12',trim(' 《Hi歌》'),trim(' 《Hi歌》第二期完整版:姚贝娜旋铃木两代好声音同台差距大'));
insert into bellawiki_file (`url`,`name`) values (trim('http://v.qq.com/cover/l/l0tmyon4rqb0alh.html'),trim('Hi歌 2014-11-13期 完整版：姚贝娜旋灵木两代好声音同台差距大'),