insert into bellawiki_work (`date`, `title`) values('2014-1-15', ' 微博之夜微博年度人气奖 （获奖）');
insert into bellawiki_work (`date`, `title`) values('2014-3-05', 'Music Radio北京发布会');
insert into bellawiki_work (`date`, `title`) values('2014-3-11', '真维斯搜狐视频合作发布会');
insert into bellawiki_work (`date`, `title`) values('2014-3-13', 'music radio沈阳拉票会');
insert into bellawiki_work (`date`, `title`) values('2014-3-19', ' 音乐风云榜年度盛典最受欢迎新人 （提名）');
insert into bellawiki_work (`date`, `title`) values('2014-3-29', '湖北汉川汉海好声音');
insert into bellawiki_work (`date`, `title`) values('2014-3-30', '镇江三山旅游名胜推介发布会');
insert into bellawiki_work (`date`, `title`) values('2014-4-02', '姚贝娜 798艺术区 拍摄致炫白色惊喜宣传片微电影');
insert into bellawiki_work (`date`, `title`) values('2014-4-01', '《beautiful light》mv拍摄');
insert into bellawiki_work (`date`, `title`) values('2014-4-03', '南昌万达城商演');
insert into bellawiki_work (`date`, `title`) values('2014-4-12', '央视全球中文音乐榜上榜《随它吧》');
insert into bellawiki_work (`date`, `title`) values('2014-4-13', '浙江奥克斯空调20周年庆');
insert into bellawiki_work (`date`, `title`) values('2014-4-15', '爱的小桔灯儿童关爱行动');
insert into bellawiki_work (`date`, `title`) values('2014-4-18', 'MR金曲网络演唱会北京');
insert into bellawiki_work (`date`, `title`) values('2014-4-19', '武汉汉街致炫体验会');
insert into bellawiki_work (`date`, `title`) values('2014-4-21', '东乐计划发布会');
insert into bellawiki_work (`date`, `title`) values('2014-4-22', '艺术人生节目录制');
insert into bellawiki_work (`date`, `title`) values('2014-4-26', 'MR中国TOP榜颁奖礼');
insert into bellawiki_work (`date`, `title`) values('2014-4-27', '北京爱琴海EP签售会');
insert into bellawiki_work (`date`, `title`) values('2014-4-28', '镇江大型水景秀白蛇传');
insert into bellawiki_work (`date`, `title`) values('2014-4-30', '郑州曼哈顿签唱会');
insert into bellawiki_work (`date`, `title`) values('2014-5-01', '中国喜剧力量节目录制');
insert into bellawiki_work (`date`, `title`) values('2014-5-02', '江西上饶群星演唱会');
insert into bellawiki_work (`date`, `title`) values('2014-5-06', 'MR校园行北京中国农大');
insert into bellawiki_work (`date`, `title`) values('2014-5-08', '上海.风尚志.活动');
insert into bellawiki_work (`date`, `title`) values('2014-5-09', 'OOH广告创意大赛颁奖礼');
insert into bellawiki_work (`date`, `title`) values('2014-5-11', '合肥红星美凯龙EP签售');
insert into bellawiki_work (`date`, `title`) values('2014-5-17', '首届中国新歌榜颁奖盛典');
insert into bellawiki_work (`date`, `title`) values('2014-5-20', '中国文艺志愿者公益宣传');
insert into bellawiki_work (`date`, `title`) values('2014-5-22', ' 城市至尊音乐榜');
insert into bellawiki_work (`date`, `title`) values('2014-5-24', '助阵好声音湖北晋级赛');
insert into bellawiki_work (`date`, `title`) values('2014-5-30', '香港音乐节');
insert into bellawiki_work (`date`, `title`) values('2014-5-31', '福州泰禾广场开业演出');
insert into bellawiki_work (`date`, `title`) values('2014-6-01', '江苏如皋演出');
insert into bellawiki_work (`date`, `title`) values('2014-6-04', '京东万和电气上门送礼活动');
insert into bellawiki_work (`date`, `title`) values('2014-6-07', '华谊20周年庆');
insert into bellawiki_work (`date`, `title`) values('2014-6-09', '搜狐视频世界杯开播仪式');
insert into bellawiki_work (`date`, `title`) values('2014-6-14', '江苏泰州群星演唱会');
insert into bellawiki_work (`date`, `title`) values('2014-6-15', '华谊ELLE之夜');
insert into bellawiki_work (`date`, `title`) values('2014-6-16', '#黄焖世界杯# 节目录制');
insert into bellawiki_work (`date`, `title`) values('2014-6-18', '浙江卫视助唱我不是明星');
insert into bellawiki_work (`date`, `title`) values('2014-6-20', '周口群星演唱会');
insert into bellawiki_work (`date`, `title`) values('2014-6-21', '城市至尊音乐盛典');
insert into bellawiki_work (`date`, `title`) values('2014-6-25', '高姿&风尚志明星盛典');
insert into bellawiki_work (`date`, `title`) values('2014-6-28', '北京潮白河演出');
insert into bellawiki_work (`date`, `title`) values('2014-6-29', '深圳星河集团演出');
insert into bellawiki_work (`date`, `title`) values('2014-8-08', '福建莆田');
insert into bellawiki_work (`date`, `title`) values('2014-8-17', '福建石狮泰禾广场');
insert into bellawiki_work (`date`, `title`) values('2014-8-22', '山西晋城');
insert into bellawiki_work (`date`, `title`) values('2014-8-27', '齐齐哈尔北大仓');
insert into bellawiki_work (`date`, `title`) values('2014-9-17', '五个一工程晚会');
insert into bellawiki_work (`date`, `title`) values('2014-9-20', '中国传媒大学校庆');
insert into bellawiki_work (`date`, `title`) values('2014-9-21', '西安万科草坪音乐会');
insert into bellawiki_work (`date`, `title`) values('2014-9-28', '上海屈臣氏演唱会');
insert into bellawiki_work (`date`, `title`) values('2014-10-09', '山西农大信院');
insert into bellawiki_work (`date`, `title`) values('2014-10-10', '湖南卫视金鹰节');
insert into bellawiki_work (`date`, `title`) values('2014-10-18', '成都金牛万达公益活动');
insert into bellawiki_work (`date`, `title`) values('2014-10-18', '广汽丰田十周年庆');
insert into bellawiki_work (`date`, `title`) values('2014-10-19', '屈臣氏广州演唱会');
insert into bellawiki_work (`date`, `title`) values('2014-10-23', ' 腾讯视频《Hi》歌录制');
insert into bellawiki_work (`date`, `title`) values('2014-10-26', '宝清商演');
insert into bellawiki_work (`date`, `title`) values('2014-12-20', ' 百度沸点飞跃成就歌手奖 （获奖）');